name: robofish-nn
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - pandas
  - tqdm
  - numpy
  - torchvision
  - python=3.8
  - matplotlib
  - pytorch
  - scikit-image
  - mlflow
    